spring.application.name=gatherindb
spring.datasource.url=jdbc:mysql://localhost:3306/gatherindb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sidhu1@S
spring.jpa.hibernate.ddl-auto=update
cloudinary.cloud-name=dl3omxod3
cloudinary.api-key=323595612939337
cloudinary.api-secret=uFD1KcHBrya-pvCQT3Oxllcn3o8