spring.application.name=gatherindb
spring.datasource.url=jdbc:mysql://localhost:3306/gatherindb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sidhu1@S
spring.jpa.hibernate.ddl-auto=update